name: Check and Test

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  run_tests:

    name: Test `cargo check/test` on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#      - name: Install minimal Rust
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable

      - name: Install libheif
        run: |
          add-apt-repository -y ppa:strukturag/libheif

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libheif-dev libdav1d-dev
          version: 1.0

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: Run tests
        run: |
          cargo check
          cargo test
